export const CHANGE_MAIN_SECTION = 'CHANGE_MAIN_SECTION'

// Search
export const SEARCH_TERM_CHANGED = 'SEARCH_TERM_CHANGED'

// AUTH
export const RECEIVED_LOGIN_AUTH_DETAILS = 'RECEIVED_LOGIN_AUTH_DETAILS'
export const LOG_OUT = 'LOG_OUT'

export const RECEIVED_OLD_USER_LOGIN_DETAILS = 'RECEIVED_OLD_USER_LOGIN_DETAILS'

// User
export const RECEIVED_USER_DETAILS = 'RECEIVED_USER_DETAILS'
export const RECEIVED_USERS = 'RECEIVED_USERS'
export const RECEIVED_USER_ACTIVITY = 'RECEIVED_USER_ACTIVITY'
export const RECEIVED_FRIEND_REQUESTS = 'RECEIVED_FRIEND_REQUESTS'
export const SENT_FRIEND_REQUEST = 'SENT_FRIEND_REQUEST'
export const CANCELED_FRIEND_REQUEST = 'CANCELED_FRIEND_REQUEST'
export const ACCEPTED_FRIEND_REQUEST = 'ACCEPTED_FRIEND_REQUEST'

// Social
export const RECIEVED_TIMELINE_POSTS = 'RECIEVED_TIMELINE_POSTS'
export const LIKED_POST = 'LIKED_POST'
export const CREATED_COMMENT = 'CREATED_COMMENT'

// Event
export const RECEIVED_COMPLETED_EVENTS = 'RECEIVED_COMPLETED_EVENTS'
export const RECEIVED_ONGOING_EVENTS = 'RECEIVED_ONGOING_EVENTS'
export const LIKED_EVENT = 'LIKED_EVENT'

// Payment
export const RECEIVED_MEMBERSHIP_PAYMENT = 'RECEIVED_MEMBERSHIP_PAYMENT'
