export const USER_LOGGED_IN = 'USER_LOGGED_IN'
export const USER_LOGGED_OUT = 'USER_LOGGED_OUT'
export const USER_PROFILE = 'USER_PROFILE';

// signup types 
export const CONTREG = 'CONTREG'
export const CONTREG2 = 'CONTREG2'
export const CONTREG3 = 'CONTREG3'
export const CONTREG4 = 'CONTREG4'
export const CONTREG5 = 'CONTREG5'
export const CONTREG6 = 'CONTREG6'
export const CURRENT_PROJECTS = 'CURRENT_PROJECTS'
export const COMPLETED_PROJECTS = 'COMPLETED_PROJECTS'
export const COMPLETED_EVENTS = 'COMPLETED_EVENTS'
export const CURRENT_EVENTS = 'CURRENT_EVENTS'
export const USER_ACTIVITY = 'USER_ACTIVITY'
export const USER_FRIENDS = 'USER_FRIENDS'